_Title "QORBLE"
_ConsoleTitle "QORBLE"

Randomize Timer
Dim WORDLIST(124) As String * 5
WORDLIST$(0) = "AWAIT"
WORDLIST$(1) = "BUNCH"
WORDLIST$(2) = "CATCH"
WORDLIST$(3) = "LUCKY"
WORDLIST$(4) = "BASIC"
WORDLIST$(5) = "PRICK"
WORDLIST$(6) = "BRICK"
WORDLIST$(7) = "ROGUE"
WORDLIST$(8) = "VOGUE"
WORDLIST$(9) = "BATCH"
WORDLIST$(10) = "WATCH"
WORDLIST$(11) = "FUDGE"
WORDLIST$(12) = "BADGE"
WORDLIST$(13) = "FOGGY"
WORDLIST$(14) = "MUGGY"
WORDLIST$(15) = "TRUCK"
WORDLIST$(16) = "AMUCK"
WORDLIST$(17) = "GRUMP"
WORDLIST$(18) = "CHAMP"
WORDLIST$(19) = "SNAKE"
WORDLIST$(20) = "CHUMP"
WORDLIST$(21) = "LONER"
WORDLIST$(22) = "TAINT"
WORDLIST$(23) = "QUIET"
WORDLIST$(24) = "QUEEN"
WORDLIST$(25) = "ELITE"
WORDLIST$(26) = "GIFTS"
WORDLIST$(27) = "HIRED"
WORDLIST$(28) = "SHIRE"
WORDLIST$(29) = "IRATE"
WORDLIST$(30) = "ELATE"
WORDLIST$(31) = "CATER"
WORDLIST$(32) = "LATHE"
WORDLIST$(33) = "BATHE"
WORDLIST$(34) = "LAYER"
WORDLIST$(35) = "MAYOR"
WORDLIST$(36) = "NAILS"
WORDLIST$(37) = "STYLE"
WORDLIST$(38) = "LIGHT"
WORDLIST$(39) = "MIGHT"
WORDLIST$(40) = "SIGHT"
WORDLIST$(41) = "FIGHT"
WORDLIST$(42) = "MANGE"
WORDLIST$(43) = "MOSSY"
WORDLIST$(44) = "BOSSY"
WORDLIST$(45) = "NIGHT"
WORDLIST$(46) = "KNIFE"
WORDLIST$(47) = "KNAVE"
WORDLIST$(48) = "NOTED"
WORDLIST$(49) = "NOTES"
WORDLIST$(50) = "STONE"
WORDLIST$(51) = "GNOME"
WORDLIST$(52) = "GONER"
WORDLIST$(53) = "LOSER"
WORDLIST$(54) = "MONEY"
WORDLIST$(55) = "NAIVE"
WORDLIST$(56) = "NUKED"
WORDLIST$(57) = "NAKED"
WORDLIST$(58) = "SNOWY"
WORDLIST$(59) = "OPERA"
WORDLIST$(60) = "OCEAN"
WORDLIST$(61) = "STATE"
WORDLIST$(62) = "OUTER"
WORDLIST$(63) = "OTTER"
WORDLIST$(64) = "OFFER"
WORDLIST$(65) = "OLIVE"
WORDLIST$(66) = "ALOOF"
WORDLIST$(67) = "ADORE"
WORDLIST$(68) = "SWORD"
WORDLIST$(69) = "SMOKE"
WORDLIST$(70) = "SHALE"
WORDLIST$(71) = "SHADE"
WORDLIST$(72) = "SHAKE"
WORDLIST$(73) = "SLEPT"
WORDLIST$(74) = "SLEEP"
WORDLIST$(75) = "SHEEP"
WORDLIST$(76) = "SCOPE"
WORDLIST$(77) = "SCOOP"
WORDLIST$(78) = "SNOOP"
WORDLIST$(79) = "QUEST"
WORDLIST$(80) = "JELLY"
WORDLIST$(81) = "JOLLY"
WORDLIST$(82) = "JAZZY"
WORDLIST$(83) = "PARTY"
WORDLIST$(84) = "PANTS"
WORDLIST$(85) = "PLANT"
WORDLIST$(86) = "PLATE"
WORDLIST$(87) = "INLET"
WORDLIST$(88) = "RISKY"
WORDLIST$(89) = "RASPY"
WORDLIST$(90) = "RUSTY"
WORDLIST$(91) = "MARSH"
WORDLIST$(92) = "SLANT"
WORDLIST$(93) = "VOICE"
WORDLIST$(94) = "CYBER"
WORDLIST$(95) = "LANCE"
WORDLIST$(96) = "FOXES"
WORDLIST$(97) = "YACHT"
WORDLIST$(98) = "UNFIT"
WORDLIST$(99) = "UPPER"
WORDLIST$(100) = "UNCLE"
WORDLIST$(101) = "UNLIT"
WORDLIST$(102) = "VALVE"
WORDLIST$(103) = "VAULT"
WORDLIST$(104) = "TROUT"
WORDLIST$(105) = "MERRY"
WORDLIST$(106) = "BERRY"
WORDLIST$(106) = "GRASP"
WORDLIST$(107) = "GRAPE"
WORDLIST$(108) = "GRATE"
WORDLIST$(109) = "GREAT"
WORDLIST$(110) = "PRANK"
WORDLIST$(111) = "LEDGE"
WORDLIST$(112) = "STEAK"
WORDLIST$(113) = "BREAK"
WORDLIST$(114) = "BRAKE"
WORDLIST$(115) = "DRAKE"
WORDLIST$(116) = "ANGEL"
WORDLIST$(117) = "ANGLE"
WORDLIST$(118) = "PIZZA"
WORDLIST$(119) = "NANNY"
WORDLIST$(120) = "SIGHT"
WORDLIST$(121) = "RIGHT"
WORDLIST$(122) = "LIGHT"
WORDLIST$(123) = "RISKY"
WORDLIST$(124) = "SPARK"


MAIN:
COLOR 7
'Chose Word
CHWORD$ = WORDLIST$(Int(Rnd * UBound(WORDLIST$)))
'Set word
Dim WORD As String * 5
WORD$(0) = Mid$(CHWORD$, 1, 1)
WORD$(1) = Mid$(CHWORD$, 2, 1)
WORD$(2) = Mid$(CHWORD$, 3, 1)
WORD$(3) = Mid$(CHWORD$, 4, 1)
WORD$(4) = Mid$(CHWORD$, 5, 1)
SUCCESS = 0
GUESSES = 0
Print "YOU HAVE SIX TRIES"
Print "GUESS A FIVE LETTER WORD: "
While SUCCESS < 5 And GUESSES < 6
    Color 15
    Input ""; GUESS$
    GUESSES = GUESSES + 1
    GoSub CHKWORD
Wend
If SUCCESS = 5 Then
    Print "CONGRATULATIONS!"
    Print
    Print "You solved it in "; GUESSES; " guess(s)!"
Else
    Print "Sorry.  The word is "; CHWORD$
End If
Print
Print "Play Again? (Y/N)"
Do
    K$ = InKey$
    If K$ = "y" Or K$ = "Y" Then
        Cls
        GoTo MAIN
    End If
Loop Until K$ <> ""
System


CHKWORD:
SUCCESS = 0
For I = 0 To 4
    EVAL$ = UCase$(Mid$(GUESS$, I + 1, 1))

    If EVAL$ = WORD$(I) Then
        Color 12
        Print EVAL$;
        SUCCESS = SUCCESS + 1
    Else
        FOUND = 0
        For j = 0 To 4
            If EVAL$ = WORD$(j) Then
                FOUND = 1
                Color 2
                Print EVAL$;
                Exit For
            End If
        Next
        If FOUND = 0 Then
            Color 15
            Print EVAL$;
        End If
    End If
Next
Color 15
Print
Return
